### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by ghost** [Hongseokzip/KakaoTalk-Bot-Boilerplate#1]
카카오톡 자동응답기를 만들어보고 싶은 생초보 개발자 지망생입니다 ㅠㅠ

한 번 사용해보고 싶은데 어떻게 사용하나요??
옐로아이디는 이미 존재합니다!

**Comment by JeonSungYun** [comment]
너무 늦게 답변을 드리게 되어 안타깝네요...ㅠㅠ
계속 코드 관리를 하지 않고 있다가, 이번에 정리하면서 참고할만한 설명 남겨두었습니다.
